In [503]:
import random as rd
import pandas as pd
import numpy as np

# Lidando com Series

In [504]:
data = [rd.randint(0, 100) for _ in range(25)]

In [505]:
s = pd.Series(data)
s.head()

0    76
1    80
2    20
3    39
4    84
dtype: int64

### Último elemento

In [506]:
s[-1:]

24    46
dtype: int64

### Potência de 2

In [507]:
s**2

0      5776
1      6400
2       400
3      1521
4      7056
5      3844
6      4356
7       361
8      6561
9      1024
10    10000
11     1296
12     8649
13     5625
14     6241
15     2304
16     9604
17     4356
18        4
19     6400
20        4
21     1369
22       36
23     5476
24     2116
dtype: int64

## Operações com Series

### Média

In [508]:
s.mean()

np.float64(56.04)

### Mediana

In [509]:
s.median()

np.float64(66.0)

### Desvio Padrão

In [510]:
s.std()

np.float64(30.459645434574576)

### Variância

In [511]:
s.var()

np.float64(927.7899999999998)

### Coeficiente de Variação

In [512]:
s.std() / s.mean()

np.float64(0.5435340013307384)

## Agregações

In [513]:
s.sum()

np.int64(1401)

In [514]:
s.count()

np.int64(25)

# DataFrames

In [515]:
df = pd.DataFrame({
    'altura': [rd.randint(100, 170) for _ in range(25)],
    'peso': [rd.randint(60, 100) for _ in range(25)],
    'idade': [rd.randint(18, 100) for _ in range(25)]
})

df.head()

   altura  peso  idade
0     116    60     56
1     117    80     66
2     137    96     57
3     120    67     21
4     153    91     67

### DataFrame Brasileiro

In [516]:
df_soccer = pd.read_html(
    "https://gist.github.com/rogernogueira/6f6f7f165e29dc45337c4b55549c61ea"
)

In [517]:
data = df_soccer[0][1].str.split(";")
columns = data[0]

In [518]:
df_soccer = pd.DataFrame(data[1:].tolist(), columns=columns)
df_soccer.head()

,ID_DELEGACIA,NOME_DEPARTAMENTO,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,ANO_BO,NUM_BO,VERSAO,NOME_DEPARTAMENTO_CIRC,NOME_SECCIONAL_CIRC,...,DESCR_UNIDADE,QUANTIDADE_OBJETO,MARCA_OBJETO,FLAG_BLOQUEIO,FLAG_DESBLOQUEIO,MES,ANO,,,
0,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AH3021,2,DECAP,DEL.SEC.2º SUL,...,NULL,1,Apple,S,N,1,2024,,,
1,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AH3021,2,DECAP,DEL.SEC.2º SUL,...,NULL,1,Apple,S,N,1,2024,,,
2,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AH3021,2,DECAP,DEL.SEC.2º SUL,...,Unidade,1,Apple,NULL,NULL,1,2024,,,
3,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AH3021,2,DECAP,DEL.SEC.2º SUL,...,NULL,1,Apple,S,N,1,2024,,,
4,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AH3021,2,DECAP,DEL.SEC.2º SUL,...,Unidade,1,Apple,NULL,NULL,1,2024,,,

In [519]:
columns

['ID_DELEGACIA',
 'NOME_DEPARTAMENTO',
 'NOME_SECCIONAL',
 'NOME_DELEGACIA',
 'NOME_MUNICIPIO',
 'ANO_BO',
 'NUM_BO',
 'VERSAO',
 'NOME_DEPARTAMENTO_CIRC',
 'NOME_SECCIONAL_CIRC',
 'NOME_DELEGACIA_CIRC',
 'NOME_MUNICIPIO_CIRC',
 'DATA_OCORRENCIA_BO',
 'HORA_OCORRENCIA',
 'DESCRICAO_APRESENTACAO',
 'DATAHORA_REGISTRO_BO',
 'DATA_COMUNICACAO_BO',
 'DATAHORA_IMPRESSAO_BO',
 'DESCR_PERIODO',
 'AUTORIA_BO',
 'FLAG_INTOLERANCIA',
 'TIPO_INTOLERANCIA',
 'FLAG_FLAGRANTE',
 'FLAG_STATUS',
 'DESC_LEI',
 'FLAG_ATO_INFRACIONAL',
 'RUBRICA',
 'DESCR_CONDUTA',
 'DESDOBRAMENTO',
 'CIRCUNSTANCIA',
 'DESCR_TIPOLOCAL',
 'DESCR_SUBTIPOLOCAL',
 'CIDADE',
 'BAIRRO',
 'CEP',
 'LOGRADOURO_VERSAO',
 'LOGRADOURO',
 'NUMERO_LOGRADOURO',
 'LATITUDE',
 'LONGITUDE',
 'CONT_OBJETO',
 'DESCR_MODO_OBJETO',
 'DESCR_TIPO_OBJETO',
 'DESCR_SUBTIPO_OBJETO',
 'DESCR_UNIDADE',
 'QUANTIDADE_OBJETO',
 'MARCA_OBJETO',
 'FLAG_BLOQUEIO',
 'FLAG_DESBLOQUEIO',
 'MES',
 'ANO',
 '',
 '',
 '']

In [520]:
df_soccer.drop(columns=[''], inplace=True)
df_soccer

,ID_DELEGACIA,NOME_DEPARTAMENTO,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,ANO_BO,NUM_BO,VERSAO,NOME_DEPARTAMENTO_CIRC,NOME_SECCIONAL_CIRC,...,DESCR_MODO_OBJETO,DESCR_TIPO_OBJETO,DESCR_SUBTIPO_OBJETO,DESCR_UNIDADE,QUANTIDADE_OBJETO,MARCA_OBJETO,FLAG_BLOQUEIO,FLAG_DESBLOQUEIO,MES,ANO
0,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AH3021,2,DECAP,DEL.SEC.2º SUL,...,Subtraído,Telecomunicação,Telefone Celular,NULL,1,Apple,S,N,1,2024
1,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AH3021,2,DECAP,DEL.SEC.2º SUL,...,Subtraído,Telecomunicação,Telefone Celular,NULL,1,Apple,S,N,1,2024
2,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AH3021,2,DECAP,DEL.SEC.2º SUL,...,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,Apple,NULL,NULL,1,2024
3,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AH3021,2,DECAP,DEL.SEC.2º SUL,...,Subtraído,Telecomunicação,Telefone Celular,NULL,1,Apple,S,N,1,2024
4,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AH3021,2,DECAP,DEL.SEC.2º SUL,...,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,Apple,NULL,NULL,1,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1810,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AE8447,1,DECAP,DEL.SEC.3º OESTE,...,Subtraído,Telecomunicação,Telefone Celular,NULL,1,Motorola,S,N,1,2024
1811,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AF3843,1,DECAP,DEL.SEC.3º OESTE,...,Subtraído,Telecomunicação,Telefone Celular,NULL,1,Samsung,S,N,1,2024
1812,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AF6829,1,DECAP,DEL.SEC.3º OESTE,...,Subtraído,Telecomunicação,Telefone Celular,NULL,1,Samsung,S,N,1,2024
1813,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AF8230,1,DECAP,DEL.SEC.3º OESTE,...,Subtraído,Telecomunicação,Telefone Celular,NULL,1,Apple,S,N,1,2024
1814,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AF8303,1,DECAP,DEL.SEC.3º OESTE,...,Subtraído,Telecomunicação,Telefone Celular,NULL,1,Motorola,N,N,1,2024

In [521]:
df_soccer.dropna(inplace=True)
df_soccer

,ID_DELEGACIA,NOME_DEPARTAMENTO,NOME_SECCIONAL,NOME_DELEGACIA,NOME_MUNICIPIO,ANO_BO,NUM_BO,VERSAO,NOME_DEPARTAMENTO_CIRC,NOME_SECCIONAL_CIRC,...,DESCR_MODO_OBJETO,DESCR_TIPO_OBJETO,DESCR_SUBTIPO_OBJETO,DESCR_UNIDADE,QUANTIDADE_OBJETO,MARCA_OBJETO,FLAG_BLOQUEIO,FLAG_DESBLOQUEIO,MES,ANO
0,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AH3021,2,DECAP,DEL.SEC.2º SUL,...,Subtraído,Telecomunicação,Telefone Celular,NULL,1,Apple,S,N,1,2024
1,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AH3021,2,DECAP,DEL.SEC.2º SUL,...,Subtraído,Telecomunicação,Telefone Celular,NULL,1,Apple,S,N,1,2024
2,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AH3021,2,DECAP,DEL.SEC.2º SUL,...,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,Apple,NULL,NULL,1,2024
3,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AH3021,2,DECAP,DEL.SEC.2º SUL,...,Subtraído,Telecomunicação,Telefone Celular,NULL,1,Apple,S,N,1,2024
4,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AH3021,2,DECAP,DEL.SEC.2º SUL,...,Subtraído,Telecomunicação,Telefone Celular,Unidade,1,Apple,NULL,NULL,1,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1810,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AE8447,1,DECAP,DEL.SEC.3º OESTE,...,Subtraído,Telecomunicação,Telefone Celular,NULL,1,Motorola,S,N,1,2024
1811,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AF3843,1,DECAP,DEL.SEC.3º OESTE,...,Subtraído,Telecomunicação,Telefone Celular,NULL,1,Samsung,S,N,1,2024
1812,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AF6829,1,DECAP,DEL.SEC.3º OESTE,...,Subtraído,Telecomunicação,Telefone Celular,NULL,1,Samsung,S,N,1,2024
1813,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AF8230,1,DECAP,DEL.SEC.3º OESTE,...,Subtraído,Telecomunicação,Telefone Celular,NULL,1,Apple,S,N,1,2024
1814,900020,DIPOL - DEPTO DE INTELIGENCIA,DELEGACIA ELETRONICA,DELEGACIA ELETRONICA,S.PAULO,2024,AF8303,1,DECAP,DEL.SEC.3º OESTE,...,Subtraído,Telecomunicação,Telefone Celular,NULL,1,Motorola,N,N,1,2024

In [522]:
df_soccer['DESCR_UNIDADE'] = df_soccer['DESCR_UNIDADE'].str.strip()
df_soccer['DESCR_UNIDADE'] = df_soccer['DESCR_UNIDADE'].apply(lambda x: np.nan if x == 'NULL' else x)
df_soccer['DESCR_UNIDADE'].unique()

<ArrowStringArray>
[nan, 'Unidade']
Length: 2, dtype: str

In [523]:
df_soccer.info()

<class 'pandas.DataFrame'>
RangeIndex: 1815 entries, 0 to 1814
Data columns (total 51 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID_DELEGACIA            1815 non-null   str
 1   NOME_DEPARTAMENTO       1815 non-null   str
 2   NOME_SECCIONAL          1815 non-null   str
 3   NOME_DELEGACIA          1815 non-null   str
 4   NOME_MUNICIPIO          1815 non-null   str
 5   ANO_BO                  1815 non-null   str
 6   NUM_BO                  1815 non-null   str
 7   VERSAO                  1815 non-null   str
 8   NOME_DEPARTAMENTO_CIRC  1815 non-null   str
 9   NOME_SECCIONAL_CIRC     1815 non-null   str
 10  NOME_DELEGACIA_CIRC     1815 non-null   str
 11  NOME_MUNICIPIO_CIRC     1815 non-null   str
 12  DATA_OCORRENCIA_BO      1815 non-null   str
 13  HORA_OCORRENCIA         1815 non-null   str
 14  DESCRICAO_APRESENTACAO  1815 non-null   str
 15  DATAHORA_REGISTRO_BO    1815 non-null   str
 16  DATA_COMUNICACAO_BO     1815 non-null   str
 17  DATAHORA_IMPRESSAO_BO   1815 non-null   str
 18  DESCR_PERIODO           1815 non-null   str
 19  AUTORIA_BO              1815 non-null   str
 20  FLAG_INTOLERANCIA       1815 non-null   str
 21  TIPO_INTOLERANCIA       1815 non-null   str
 22  FLAG_FLAGRANTE          1815 non-null   str
 23  FLAG_STATUS             1815 non-null   str
 24  DESC_LEI                1815 non-null   str
 25  FLAG_ATO_INFRACIONAL    1815 non-null   str
 26  RUBRICA                 1815 non-null   str
 27  DESCR_CONDUTA           1815 non-null   str
 28  DESDOBRAMENTO           1815 non-null   str
 29  CIRCUNSTANCIA           1815 non-null   str
 30  DESCR_TIPOLOCAL         1815 non-null   str
 31  DESCR_SUBTIPOLOCAL      1815 non-null   str
 32  CIDADE                  1815 non-null   str
 33  BAIRRO                  1815 non-null   str
 34  CEP                     1815 non-null   str
 35  LOGRADOURO_VERSAO       1815 non-null   str
 36  LOGRADOURO              1815 non-null   str
 37  NUMERO_LOGRADOURO       1815 non-null   str
 38  LATITUDE                1815 non-null   str
 39  LONGITUDE               1815 non-null   str
 40  CONT_OBJETO             1815 non-null   str
 41  DESCR_MODO_OBJETO       1815 non-null   str
 42  DESCR_TIPO_OBJETO       1815 non-null   str
 43  DESCR_SUBTIPO_OBJETO    1815 non-null   str
 44  DESCR_UNIDADE           465 non-null    str
 45  QUANTIDADE_OBJETO       1815 non-null   str
 46  MARCA_OBJETO            1815 non-null   str
 47  FLAG_BLOQUEIO           1815 non-null   str
 48  FLAG_DESBLOQUEIO        1815 non-null   str
 49  MES                     1815 non-null   str
 50  ANO                     1815 non-null   str
dtypes: str(51)
memory usage: 1.5 MB